### ISSUE TITLE
Can't Install using pip

### ISSUE THREAD

**Issue by cesaremorel** [shauser/mkdocs-pdf-export-plugin#4]
Im trying to install this plugin following instructions but pip launch an error:

```
$ sudo pip install -vvvv mkdocs-pdf-export-plugin
The directory '/home/foobar/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/foobar/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mkdocs-pdf-export-plugin
  1 location(s) to search for versions of mkdocs-pdf-export-plugin:
  * https://pypi.python.org/simple/mkdocs-pdf-export-plugin/
  Getting page https://pypi.python.org/simple/mkdocs-pdf-export-plugin/
  Looking up "https://pypi.python.org/simple/mkdocs-pdf-export-plugin/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/mkdocs-pdf-export-plugin/ HTTP/1.1" 301 122
  Updating cache with response from "https://pypi.python.org/simple/mkdocs-pdf-export-plugin/"
  Caching permanant redirect
  Looking up "https://pypi.org/simple/mkdocs-pdf-export-plugin/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/mkdocs-pdf-export-plugin/ HTTP/1.1" 404 13
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/mkdocs-pdf-export-plugin/: 404 Client Error: Not Found for url: https://pypi.org/simple/mkdocs-pdf-export-plugin/ - skipping
  Could not find a version that satisfies the requirement mkdocs-pdf-export-plugin (from versions: )
Cleaning up...
No matching distribution found for mkdocs-pdf-export-plugin
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for mkdocs-pdf-export-plugin

```

**Comment by shauser** [comment]
Sorry about that. The plugin was basically an internal code dump for now. I always wanted to fix a few issues and do a refactoring before releasing 0.1 but I never got around to actually do that though.

For now the only way to install it is to clone it from the repo. However you should definitely expect some rough edges until I release 0.1:

    pip install git+https://github.com/shauser/mkdocs-pdf-export-plugin.git

I hope to have the time to get to release an actually fully working plugin some time soon, but I can't guarantee it.

**Comment by shauser** [comment]
And fixed.
